# Generated by Django 3.0.4 on 2020-04-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200428_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
    ]
